#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export TASK4_CLOSETOP_TO_OPENMIDDLE_TELEPORT=1
export TASK4_OPEN_MIDDLE_RELEASE_ANCHOR_FRAME=20
export TASK4_CLOSEMIDDLE_TO_OPENBOTTOM_TELEPORT=1
export TASK4_OPEN_BOTTOM_RELEASE_ANCHOR_FRAME=20
export TASK4_CLOSEBOTTOM_TO_OPENTOPAGAIN_TELEPORT=1
export TASK4_OPEN_TOP_AGAIN_RELEASE_ANCHOR_FRAME=50
exec bash "${ROOT}/scripts/run_task_20ep.sh" 4 "${NUM_TRIALS:-1}" "${SEED:-108}" "${PORT:-9656}"
